/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TvSeriesRouteImport } from './routes/tv-series'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopRatedRouteImport } from './routes/top-rated'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NollywoodRouteImport } from './routes/nollywood'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as KoreanDramaRouteImport } from './routes/korean-drama'
import { Route as HollywoodRouteImport } from './routes/hollywood'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ChineseDramaRouteImport } from './routes/chinese-drama'
import { Route as BollywoodRouteImport } from './routes/bollywood'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as TrailerIdRouteImport } from './routes/trailer.$id'
import { Route as TmdbIdRouteImport } from './routes/tmdb.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSeriesRoute = TvSeriesRouteImport.update({
  id: '/tv-series',
  path: '/tv-series',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedRoute = TopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NollywoodRoute = NollywoodRouteImport.update({
  id: '/nollywood',
  path: '/nollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const KoreanDramaRoute = KoreanDramaRouteImport.update({
  id: '/korean-drama',
  path: '/korean-drama',
  getParentRoute: () => rootRouteImport,
} as any)
const HollywoodRoute = HollywoodRouteImport.update({
  id: '/hollywood',
  path: '/hollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ChineseDramaRoute = ChineseDramaRouteImport.update({
  id: '/chinese-drama',
  path: '/chinese-drama',
  getParentRoute: () => rootRouteImport,
} as any)
const BollywoodRoute = BollywoodRouteImport.update({
  id: '/bollywood',
  path: '/bollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerIdRoute = TrailerIdRouteImport.update({
  id: '/trailer/$id',
  path: '/trailer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TmdbIdRoute = TmdbIdRouteImport.update({
  id: '/tmdb/$id',
  path: '/tmdb/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime': typeof AnimeRoute
  '/bollywood': typeof BollywoodRoute
  '/chinese-drama': typeof ChineseDramaRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/dmca': typeof DmcaRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/hollywood': typeof HollywoodRoute
  '/korean-drama': typeof KoreanDramaRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/nollywood': typeof NollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/tv-series': typeof TvSeriesRoute
  '/upload': typeof UploadRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/tmdb/$id': typeof TmdbIdRoute
  '/trailer/$id': typeof TrailerIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime': typeof AnimeRoute
  '/bollywood': typeof BollywoodRoute
  '/chinese-drama': typeof ChineseDramaRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/dmca': typeof DmcaRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/hollywood': typeof HollywoodRoute
  '/korean-drama': typeof KoreanDramaRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/nollywood': typeof NollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/tv-series': typeof TvSeriesRoute
  '/upload': typeof UploadRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/tmdb/$id': typeof TmdbIdRoute
  '/trailer/$id': typeof TrailerIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anime': typeof AnimeRoute
  '/bollywood': typeof BollywoodRoute
  '/chinese-drama': typeof ChineseDramaRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/dmca': typeof DmcaRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/history': typeof HistoryRoute
  '/hollywood': typeof HollywoodRoute
  '/korean-drama': typeof KoreanDramaRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/nollywood': typeof NollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/tv-series': typeof TvSeriesRoute
  '/upload': typeof UploadRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/tmdb/$id': typeof TmdbIdRoute
  '/trailer/$id': typeof TrailerIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anime'
    | '/bollywood'
    | '/chinese-drama'
    | '/coming-soon'
    | '/contact'
    | '/countries'
    | '/dmca'
    | '/downloads'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/genres'
    | '/history'
    | '/hollywood'
    | '/korean-drama'
    | '/latest'
    | '/login'
    | '/movies'
    | '/nollywood'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/top-rated'
    | '/trending'
    | '/tv-series'
    | '/upload'
    | '/watchlist'
    | '/movie/$id'
    | '/tmdb/$id'
    | '/trailer/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anime'
    | '/bollywood'
    | '/chinese-drama'
    | '/coming-soon'
    | '/contact'
    | '/countries'
    | '/dmca'
    | '/downloads'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/genres'
    | '/history'
    | '/hollywood'
    | '/korean-drama'
    | '/latest'
    | '/login'
    | '/movies'
    | '/nollywood'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/top-rated'
    | '/trending'
    | '/tv-series'
    | '/upload'
    | '/watchlist'
    | '/movie/$id'
    | '/tmdb/$id'
    | '/trailer/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anime'
    | '/bollywood'
    | '/chinese-drama'
    | '/coming-soon'
    | '/contact'
    | '/countries'
    | '/dmca'
    | '/downloads'
    | '/faq'
    | '/favorites'
    | '/forgot-password'
    | '/genres'
    | '/history'
    | '/hollywood'
    | '/korean-drama'
    | '/latest'
    | '/login'
    | '/movies'
    | '/nollywood'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/top-rated'
    | '/trending'
    | '/tv-series'
    | '/upload'
    | '/watchlist'
    | '/movie/$id'
    | '/tmdb/$id'
    | '/trailer/$id'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnimeRoute: typeof AnimeRoute
  BollywoodRoute: typeof BollywoodRoute
  ChineseDramaRoute: typeof ChineseDramaRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  DmcaRoute: typeof DmcaRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GenresRoute: typeof GenresRoute
  HistoryRoute: typeof HistoryRoute
  HollywoodRoute: typeof HollywoodRoute
  KoreanDramaRoute: typeof KoreanDramaRoute
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  NollywoodRoute: typeof NollywoodRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TopRatedRoute: typeof TopRatedRoute
  TrendingRoute: typeof TrendingRoute
  TvSeriesRoute: typeof TvSeriesRoute
  UploadRoute: typeof UploadRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieIdRoute: typeof MovieIdRoute
  TmdbIdRoute: typeof TmdbIdRoute
  TrailerIdRoute: typeof TrailerIdRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-series': {
      id: '/tv-series'
      path: '/tv-series'
      fullPath: '/tv-series'
      preLoaderRoute: typeof TvSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated': {
      id: '/top-rated'
      path: '/top-rated'
      fullPath: '/top-rated'
      preLoaderRoute: typeof TopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nollywood': {
      id: '/nollywood'
      path: '/nollywood'
      fullPath: '/nollywood'
      preLoaderRoute: typeof NollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korean-drama': {
      id: '/korean-drama'
      path: '/korean-drama'
      fullPath: '/korean-drama'
      preLoaderRoute: typeof KoreanDramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hollywood': {
      id: '/hollywood'
      path: '/hollywood'
      fullPath: '/hollywood'
      preLoaderRoute: typeof HollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinese-drama': {
      id: '/chinese-drama'
      path: '/chinese-drama'
      fullPath: '/chinese-drama'
      preLoaderRoute: typeof ChineseDramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollywood': {
      id: '/bollywood'
      path: '/bollywood'
      fullPath: '/bollywood'
      preLoaderRoute: typeof BollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer/$id': {
      id: '/trailer/$id'
      path: '/trailer/$id'
      fullPath: '/trailer/$id'
      preLoaderRoute: typeof TrailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmdb/$id': {
      id: '/tmdb/$id'
      path: '/tmdb/$id'
      fullPath: '/tmdb/$id'
      preLoaderRoute: typeof TmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnimeRoute: AnimeRoute,
  BollywoodRoute: BollywoodRoute,
  ChineseDramaRoute: ChineseDramaRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  DmcaRoute: DmcaRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GenresRoute: GenresRoute,
  HistoryRoute: HistoryRoute,
  HollywoodRoute: HollywoodRoute,
  KoreanDramaRoute: KoreanDramaRoute,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  NollywoodRoute: NollywoodRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TopRatedRoute: TopRatedRoute,
  TrendingRoute: TrendingRoute,
  TvSeriesRoute: TvSeriesRoute,
  UploadRoute: UploadRoute,
  WatchlistRoute: WatchlistRoute,
  MovieIdRoute: MovieIdRoute,
  TmdbIdRoute: TmdbIdRoute,
  TrailerIdRoute: TrailerIdRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
